### ISSUE TITLE
Doesn't work after installing through admin interface

### ISSUE THREAD

**Issue by dotted** [WhateverSkynet/nodebb-plugin-moonlight#8]
From log when building assets
````
28/5 14:31:57 [26445] - error: Build failed: Error: ENOENT: no such file or directory, stat '/home/systemfailure/nodebb/node_modules/react/dist/react.min.js'
[cluster] Child Process (26445) has exited (code: 1, signal: null)
````

From log file when accessing the admin page for moonlight
````
28/5 14:33:01 [26558] - error: /admin/plugins/moonlight
 Error: Failed to lookup view "admin/plugins/moonlight" in views directory "/home/systemfailure/nodebb/build/public/templates"
    at Function.render (/home/systemfailure/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/home/systemfailure/nodebb/node_modules/express/lib/response.js:971:7)
    at content (/home/systemfailure/nodebb/src/middleware/render.js:70:15)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:3830:24
    at replenish (/home/systemfailure/nodebb/node_modules/async/dist/async.js:946:17)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:950:9
    at eachOfLimit (/home/systemfailure/nodebb/node_modules/async/dist/async.js:975:24)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:980:16
    at eachOf (/home/systemfailure/nodebb/node_modules/async/dist/async.js:1051:5)
    at _parallel (/home/systemfailure/nodebb/node_modules/async/dist/async.js:3829:5)
    at Object.parallelLimit [as parallel] (/home/systemfailure/nodebb/node_modules/async/dist/async.js:3912:5)
    at async.waterfall.str (/home/systemfailure/nodebb/src/middleware/render.js:65:12)
    at nextTask (/home/systemfailure/nodebb/node_modules/async/dist/async.js:5274:14)
    at next (/home/systemfailure/nodebb/node_modules/async/dist/async.js:5281:9)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:906:16
    at fireFilterHook (/home/systemfailure/nodebb/src/plugins/hooks.js:110:11)
````

My guess is that it is because you have a lot of runtime dependencies in your devDependencies, so most dependencies never get installed on my installation

**Comment by dotted** [comment]
Tried to work around the issue by installing the dependencies manually:
````
npm i react@15.4.2 react-dom@15.4.2 react-addons-css-transition-group@15.4.2 react-addons-pure-render-mixin@15.4.2 react-css-themr@1.1.3 react-redux@5.0.2 react-router@3.0.2 react-router-redux@4.0.7 react-tap-event-plugin@2.0.1 redux@3.6.0 redux-form@6.5.0 redux-observable@0.13.0 rxjs@5.1.0 normalize.css@5.0.0 material-ui@0.17.4
````
But now i get this error
````
28/5 15:03:28 [29187] - error: Build failed: Error: ENOENT: no such file or directory, stat '/home/systemfailure/nodebb/node_modules/nodebb-plugin-moonlight/dist/main.map.js'
````

**Comment by dotted** [comment]
Manually copying the *.map.js to *.map gives my this error on build

````
28/5 18:09:08 [9292] - error: Build failed: SyntaxError: Unexpected character '@'
    at JS_Parse_Error.get (eval at <anonymous> (/home/systemfailure/nodebb/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:86:23)
    at step (/home/systemfailure/nodebb/src/meta/build.js:55:40)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:3838:9
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/home/systemfailure/nodebb/node_modules/async/dist/async.js:924:17)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:906:16
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:3835:13
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:421:16
    at next (/home/systemfailure/nodebb/node_modules/async/dist/async.js:5278:29)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:906:16
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/home/systemfailure/nodebb/node_modules/async/dist/async.js:924:17)
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:906:16
    at /home/systemfailure/nodebb/src/meta/js.js:131:13
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:3838:9
    at /home/systemfailure/nodebb/node_modules/async/dist/async.js:421:16
````

**Comment by voicis** [comment]
Hi, at the moment this plugin is made for one particular site and tied to a particular design. Although, I've not seen the errors you have listed above, getting the plugin work initially is not quite straight forward. It currently has the following features:
- Private guild application process.
- Guild news/blog.

If you're still interested in this I can help you to get it running.

**Comment by dotted** [comment]
I'd very interested

**Comment by voicis** [comment]
What version of NodeBB are you using?
Are you by any chance using Discord? It would speed up the process.

**Comment by dotted** [comment]
1.5.0 and yes dotted#0594

**Comment by voicis** [comment]
It actually might be easier to get it running than I initially thought. I've made some changes how the plugin files are loaded (in the browser).

Please try to install 0.2.17 version, it should work without any other modifications. (You need to force NodeBB to rebuild assets)
You will also need the following user groups for the plugin to work:
- officers
- raiders
- trials

**Comment by dotted** [comment]
Nice, I can access admin page now. But I can see what you mean by being made for a specific design: http://systemfailure.dk/ (This is supposedly the Persona theme) :)

So issues I've found so far:
- I needed to install nodebb-plugin-calendar (Was getting 404's in the javascript console referring to it)
- Logs menu option is hardcoded to your guilds logs, as far as I can tell.
- Can't set API key it seems, if i navigate away from the Blizzard Api page and then back again the Api key has disappeared. the other values persists however.
- Possibly related to the Api key issue, when importing the roster I get a toast message saying my account has expired.

I took the liberty of registering on your guild website, and yes this is definitely what I'm looking for, so thanks for the plugin and help. I'll be going to bed now, but I'll try and see if I can find more issues tommorow.

**Comment by voicis** [comment]
- Now it should be possible to save Blizzard Api key.
- You are right, roster update was most likely failing because of the missing API key. Depending on how many characters are in the guild, the update might take a while.

- I could not find any references to the nodebb-plugin-calendar and it should not be needed. Can you please post the stack trace of the error?
- Current implementation of navigation will not work for generic solution. Once the custom navigation is removed you can add custom routes manually.

For the time being I suggest not to use the plugin in the production site, but use a local one for testing. Also you should get a SSL certificate for the site, you can generate certificates using https://letsencrypt.org/ for free.

**Comment by dotted** [comment]
- Api key saves, and I'm currently fetching the roster 👍 

- About nodebb-plugin-calendar it might be irrelevant, I just noticed it in the javascript console which is why i mentioned it - I'll try and experiment with it later.

As for SSL, when the site officially launches I'll remember to do that - I need it for the Battle.net authentication anyways :)
